### ISSUE TITLE
Выбивает в ошибку клавиатуры:(

### ISSUE THREAD

**Issue by sav1s** [w1png/shop-telegram-bot#11]
Выбивает в ошибку клавиатуры, перепробовал всё просто, от гугла до переустановок:)
Код ошибки:
Traceback (most recent call last):
  File "C:\Users\sav1s\Desktop\shop-telegram-bot-master\src\main.py", line 20, in <module>
    import user as usr
  File "C:\Users\sav1s\Desktop\shop-telegram-bot-master\src\user.py", line 3, in <module>
    import item as itm
  File "C:\Users\sav1s\Desktop\shop-telegram-bot-master\src\item.py", line 4, in <module>
    from main import notify_admins
  File "C:\Users\sav1s\Desktop\shop-telegram-bot-master\src\main.py", line 36, in <module>
    bot = Bot(token=settings.get_token())
  File "C:\Users\sav1s\Desktop\shop-telegram-bot-master\src\settings.py", line 23, in get_token
    return self.__get_config()["main_settings"]["token"]
  File "C:\Program Files\Python310\lib\configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'main_settings'

**Comment by w1png** [comment]
Запускаете через Docker? @sav1s

**Comment by sav1s** [comment]
Не понимаю сам, докер выкидывает иногда ошибку токена, потом ошибку создания таблицы "cats"(sqlite3.OperationalError: table "cats" already exists). Не понимаю вообще почему всё это выдаёт, на основном пк 1000% работает, начал на ноутбуке всё 1 в 1 делать, начал в ошибки выбивать Python version: 3.10.0

**Comment by w1png** [comment]
Напишите мне в тг [@w1png](https://t.me/w1png)
